name: Test pub

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.1"
      - run: pip install poetry
      - run: pip install httpx
      - run: pip install git+https://github.com/autopub/autopub.git@add-contributors-names-to-changelog
      - run: poetry version patch
      - run: autopub check
      - run: autopub deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
